In [2]:
import pandas as pd

In [4]:
pd.read_csv("data_raw/ems20_1st_6months_excerpt.csv")

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,201101264,2020-04-19 10:25:47,INJMIN,7,INJMIN,7,04/19/2020 10:26:24 AM,Y,37,04/19/2020 10:26:24 AM,...,40.0,8.0,201.0,7.0,15.0,N,N,N,N,chunk170.csv
1,200423766,2020-02-11 19:25:47,CARD,3,SICK,6,02/11/2020 07:25:56 PM,Y,9,02/11/2020 07:26:09 PM,...,52.0,14.0,207.0,10.0,15.0,N,N,N,N,chunk166.csv
2,200434110,2020-02-12 21:36:52,UNC,2,UNC,2,02/12/2020 09:37:24 PM,Y,32,02/12/2020 09:38:27 PM,...,106.0,32.0,410.0,27.0,8.0,N,N,N,N,chunk166.csv
3,201610121,2020-06-09 00:52:30,DRUG,4,DRUG,4,06/09/2020 12:52:44 AM,Y,14,06/09/2020 12:52:59 AM,...,19.0,4.0,108.0,2.0,12.0,N,N,N,N,chunk171.csv
4,200034112,2020-01-03 20:44:05,DRUG,4,DRUG,4,01/03/2020 08:44:11 PM,Y,6,01/03/2020 08:44:17 PM,...,66.0,39.0,312.0,15.0,7.0,N,N,N,N,chunk165.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13112,200393407,2020-02-08 19:49:33,DIFFBR,2,DIFFBR,2,02/08/2020 07:52:34 PM,Y,181,02/08/2020 07:53:00 PM,...,72.0,38.0,307.0,15.0,7.0,N,N,N,N,chunk166.csv
13113,200034618,2020-01-03 22:51:33,INJURY,5,INJURY,5,01/03/2020 10:51:39 PM,Y,6,01/03/2020 10:52:21 PM,...,75.0,42.0,305.0,19.0,8.0,N,N,N,N,chunk165.csv
13114,200424355,2020-02-11 21:51:09,SICK,6,SICK,6,02/11/2020 09:52:09 PM,Y,60,02/11/2020 09:52:18 PM,...,48.0,15.0,206.0,10.0,15.0,N,N,N,N,chunk166.csv
13115,201742708,2020-06-22 15:57:44,MVAINJ,4,MVAINJ,4,06/22/2020 03:58:07 PM,Y,23,06/22/2020 03:58:19 PM,...,62.0,47.0,311.0,21.0,11.0,N,N,N,N,chunk172.csv
13116,200865674,2020-03-26 19:33:19,DIFFFC,2,DIFFFC,2,03/26/2020 07:33:50 PM,Y,31,03/26/2020 07:34:08 PM,...,103.0,27.0,412.0,29.0,5.0,N,N,N,N,chunk168.csv

In [52]:
ems2020_excerpt_df = pd.read_csv("data_raw/ems20_1st_6months_excerpt.csv")

In [54]:
type(df)

pandas.core.frame.DataFrame

In [59]:
ems2020_excerpt_df.head(10)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,201101264,2020-04-19 10:25:47,INJMIN,7,INJMIN,7,04/19/2020 10:26:24 AM,Y,37,04/19/2020 10:26:24 AM,...,40.0,8.0,201.0,7.0,15.0,N,N,N,N,chunk170.csv
1,200423766,2020-02-11 19:25:47,CARD,3,SICK,6,02/11/2020 07:25:56 PM,Y,9,02/11/2020 07:26:09 PM,...,52.0,14.0,207.0,10.0,15.0,N,N,N,N,chunk166.csv
2,200434110,2020-02-12 21:36:52,UNC,2,UNC,2,02/12/2020 09:37:24 PM,Y,32,02/12/2020 09:38:27 PM,...,106.0,32.0,410.0,27.0,8.0,N,N,N,N,chunk166.csv
3,201610121,2020-06-09 00:52:30,DRUG,4,DRUG,4,06/09/2020 12:52:44 AM,Y,14,06/09/2020 12:52:59 AM,...,19.0,4.0,108.0,2.0,12.0,N,N,N,N,chunk171.csv
4,200034112,2020-01-03 20:44:05,DRUG,4,DRUG,4,01/03/2020 08:44:11 PM,Y,6,01/03/2020 08:44:17 PM,...,66.0,39.0,312.0,15.0,7.0,N,N,N,N,chunk165.csv
5,200530247,2020-02-22 01:26:18,DRUG,4,DRUG,4,02/22/2020 01:27:21 AM,Y,63,02/22/2020 01:27:41 AM,...,25.0,8.0,111.0,4.0,12.0,N,N,N,N,chunk167.csv
6,200543279,2020-02-23 19:08:27,UNC,2,UNC,2,02/23/2020 07:08:44 PM,Y,17,02/23/2020 07:09:16 PM,...,44.0,8.0,204.0,9.0,15.0,N,N,N,N,chunk167.csv
7,201471743,2020-05-26 12:45:46,INJURY,5,INJURY,5,05/26/2020 12:46:04 PM,Y,18,05/26/2020 12:46:15 PM,...,41.0,17.0,202.0,8.0,15.0,N,N,N,N,chunk171.csv
8,201180116,2020-04-27 00:57:48,EDP,7,EDPC,7,04/27/2020 12:58:07 AM,Y,19,04/27/2020 12:58:15 AM,...,50.0,11.0,208.0,10.0,16.0,N,N,N,N,chunk170.csv
9,200572739,2020-02-26 15:15:25,CARDBR,2,CARDBR,2,02/26/2020 03:16:35 PM,Y,70,02/26/2020 03:16:49 PM,...,106.0,28.0,410.0,27.0,5.0,N,N,N,N,chunk167.csv

In [61]:
ems2020_excerpt_df.tail(5)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
13112,200393407,2020-02-08 19:49:33,DIFFBR,2,DIFFBR,2,02/08/2020 07:52:34 PM,Y,181,02/08/2020 07:53:00 PM,...,72.0,38.0,307.0,15.0,7.0,N,N,N,N,chunk166.csv
13113,200034618,2020-01-03 22:51:33,INJURY,5,INJURY,5,01/03/2020 10:51:39 PM,Y,6,01/03/2020 10:52:21 PM,...,75.0,42.0,305.0,19.0,8.0,N,N,N,N,chunk165.csv
13114,200424355,2020-02-11 21:51:09,SICK,6,SICK,6,02/11/2020 09:52:09 PM,Y,60,02/11/2020 09:52:18 PM,...,48.0,15.0,206.0,10.0,15.0,N,N,N,N,chunk166.csv
13115,201742708,2020-06-22 15:57:44,MVAINJ,4,MVAINJ,4,06/22/2020 03:58:07 PM,Y,23,06/22/2020 03:58:19 PM,...,62.0,47.0,311.0,21.0,11.0,N,N,N,N,chunk172.csv
13116,200865674,2020-03-26 19:33:19,DIFFFC,2,DIFFFC,2,03/26/2020 07:33:50 PM,Y,31,03/26/2020 07:34:08 PM,...,103.0,27.0,412.0,29.0,5.0,N,N,N,N,chunk168.csv

In [63]:
ems2020_excerpt_df.sample(20)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
11133,200390326,2020-02-08 02:05:55,RESPIR,4,RESPIR,4,02/08/2020 02:06:02 AM,Y,7,02/08/2020 02:06:22 AM,...,122.0,50.0,502.0,31.0,11.0,N,N,N,N,chunk166.csv
11876,200424729,2020-02-11 23:49:37,UNKNOW,4,UNKNOW,4,02/11/2020 11:49:47 PM,Y,10,02/11/2020 11:50:58 PM,...,79.0,36.0,303.0,13.0,8.0,N,N,N,N,chunk166.csv
5926,200990385,2020-04-08 02:08:29,CARD,3,CARD,3,04/08/2020 02:08:39 AM,Y,10,04/08/2020 02:08:49 AM,...,105.0,31.0,413.0,29.0,5.0,N,N,N,N,chunk169.csv
3182,201232794,2020-05-02 18:13:30,UNKNOW,4,UNKNOW,4,05/02/2020 06:13:38 PM,Y,8,05/02/2020 06:13:59 PM,...,25.0,8.0,111.0,4.0,13.0,N,N,N,N,chunk170.csv
6542,201083986,2020-04-17 20:09:22,ASTHMB,2,ASTHMB,2,04/17/2020 08:09:50 PM,Y,28,04/17/2020 08:10:01 PM,...,48.0,15.0,206.0,12.0,15.0,N,N,N,N,chunk170.csv
8737,201273228,2020-05-06 20:39:57,INJURY,5,INJURY,5,05/06/2020 08:40:13 PM,Y,16,05/06/2020 08:40:24 PM,...,100.0,32.0,414.0,27.0,5.0,N,N,N,N,chunk170.csv
6074,200371671,2020-02-06 10:59:15,ARREST,1,ARREST,1,02/06/2020 10:59:53 AM,Y,38,02/06/2020 11:00:12 AM,...,18.0,4.0,105.0,2.0,12.0,N,N,N,N,chunk166.csv
9269,201023591,2020-04-11 17:46:20,SICKFC,6,SICKFC,6,04/11/2020 05:48:00 PM,Y,100,04/11/2020 05:48:00 PM,...,33.0,7.0,112.0,6.0,13.0,N,N,N,N,chunk169.csv
10606,200311052,2020-01-31 08:51:07,CARD,3,CARD,3,01/31/2020 08:51:13 AM,Y,6,01/31/2020 08:51:19 AM,...,73.0,42.0,316.0,23.0,9.0,N,N,N,N,chunk166.csv
12074,200993512,2020-04-08 15:03:23,SICK,6,SICK,6,04/08/2020 03:05:28 PM,Y,125,04/08/2020 03:05:28 PM,...,40.0,8.0,201.0,7.0,15.0,N,N,N,N,chunk169.csv
2702,201413636,2020-05-20 22:39:03,INJMAJ,3,INJMAJ,3,05/20/2020 10:39:24 PM,Y,21,05/20/2020 10:40:16 PM,...,46.0,14.0,205.0,10.0,15.0,N,N,N,N,chunk171.csv
1660,201112440,2020-04-20 14:56:18,INJURY,5,INJURY,5,04/20/2020 02:56:28 PM,Y,10,04/20/2020 02:57:40 PM,...,44.0,16.0,204.0,9.0,15.0,N,N,N,N,chunk170.csv
12175,200182412,2020-01-18 14:58:06,SICK,6,SICK,6,01/18/2020 02:58:15 PM,Y,9,01/18/2020 02:58:25 PM,...,9.0,2.0,103.0,1.0,12.0,N,N,N,N,chunk165.csv
5520,201790536,2020-06-27 03:13:27,CDBRFC,2,CDBRFC,2,06/27/2020 03:13:51 AM,Y,24,06/27/2020 03:14:02 AM,...,100.0,31.0,414.0,27.0,5.0,N,N,N,N,chunk172.csv
7884,201653459,2020-06-13 21:46:34,UNKNOW,4,UNKNOW,4,06/13/2020 09:47:39 PM,Y,65,06/13/2020 09:48:35 PM,...,40.0,8.0,201.0,7.0,15.0,N,N,N,N,chunk171.csv
4732,201662281,2020-06-14 16:15:27,CARDBR,2,CARDBR,2,06/14/2020 04:15:34 PM,Y,7,06/14/2020 04:15:57 PM,...,52.0,11.0,207.0,10.0,16.0,N,N,N,N,chunk171.csv
9873,200734093,2020-03-13 20:17:48,SICK,6,SICK,6,03/13/2020 08:20:41 PM,Y,173,03/13/2020 08:21:27 PM,...,41.0,17.0,202.0,12.0,15.0,N,N,N,N,chunk168.csv
10861,200573909,2020-02-26 20:14:49,DRUG,4,DRUG,4,02/26/2020 08:15:58 PM,Y,69,02/26/2020 08:16:20 PM,...,40.0,17.0,201.0,7.0,15.0,N,N,N,N,chunk167.csv
10239,201442412,2020-05-23 17:23:23,RESPIR,4,RESPIR,4,05/23/2020 05:23:28 PM,Y,5,05/23/2020 05:23:38 PM,...,46.0,15.0,205.0,9.0,15.0,N,N,N,N,chunk171.csv
1250,200840284,2020-03-24 01:26:19,SICK,6,SICMIN,7,03/24/2020 02:21:34 AM,Y,3315,03/24/2020 02:23:24 AM,...,42.0,17.0,203.0,12.0,15.0,N,N,N,N,chunk168.csv

In [65]:
ems2020_excerpt_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13117 entries, 0 to 13116
Data columns (total 32 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   CAD_INCIDENT_ID                 13117 non-null  int64
 1   INCIDENT_DATETIME               13117 non-null  object
 2   INITIAL_CALL_TYPE               13117 non-null  object
 3   INITIAL_SEVERITY_LEVEL_CODE     13117 non-null  int64
 4   FINAL_CALL_TYPE                 13117 non-null  object
 5   FINAL_SEVERITY_LEVEL_CODE       13117 non-null  int64
 6   FIRST_ASSIGNMENT_DATETIME       13010 non-null  object
 7   VALID_DISPATCH_RSPNS_TIME_INDC  13117 non-null  object
 8   DISPATCH_RESPONSE_SECONDS_QY    13117 non-null  int64
 9   FIRST_ACTIVATION_DATETIME       12988 non-null  object
 10  FIRST_ON_SCENE_DATETIME         12533 non-null  object
 11  VALID_INCIDENT_RSPNS_TIME_INDC  13117 non-null  object
 12  INCIDENT_RESPONSE_SECONDS_QY    12533 non-null  float64
 13  INCIDENT_TRAVEL_TM_SECONDS_QY   12533 non-null  float64
 14  FIRST_TO_HOSP_DATETIME          7870 non-null   object
 15  FIRST_HOSP_ARRIVAL_DATETIME     7791 non-null   object
 16  INCIDENT_CLOSE_DATETIME         13110 non-null  object
 17  HELD_INDICATOR                  13117 non-null  object
 18  INCIDENT_DISPOSITION_CODE       12985 non-null  float64
 19  BOROUGH                         13117 non-null  object
 20  INCIDENT_DISPATCH_AREA          13117 non-null  object
 21  ZIPCODE                         12987 non-null  float64
 22  POLICEPRECINCT                  12988 non-null  float64
 23  CITYCOUNCILDISTRICT             12988 non-null  float64
 24  COMMUNITYDISTRICT               12988 non-null  float64
 25  COMMUNITYSCHOOLDISTRICT         12978 non-null  float64
 26  CONGRESSIONALDISTRICT           12988 non-null  float64
 27  REOPEN_INDICATOR                13117 non-null  object
 28  SPECIAL_EVENT_INDICATOR         13117 non-null  object
 29  STANDBY_INDICATOR               13117 non-null  object
 30  TRANSFER_INDICATOR              13117 non-null  object
 31  source                          13117 non-null  object
dtypes: float64(9), int64(4), object(19)
memory usage: 3.2+ MB

In [67]:
ems2020_excerpt_df.head(7)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,201101264,2020-04-19 10:25:47,INJMIN,7,INJMIN,7,04/19/2020 10:26:24 AM,Y,37,04/19/2020 10:26:24 AM,...,40.0,8.0,201.0,7.0,15.0,N,N,N,N,chunk170.csv
1,200423766,2020-02-11 19:25:47,CARD,3,SICK,6,02/11/2020 07:25:56 PM,Y,9,02/11/2020 07:26:09 PM,...,52.0,14.0,207.0,10.0,15.0,N,N,N,N,chunk166.csv
2,200434110,2020-02-12 21:36:52,UNC,2,UNC,2,02/12/2020 09:37:24 PM,Y,32,02/12/2020 09:38:27 PM,...,106.0,32.0,410.0,27.0,8.0,N,N,N,N,chunk166.csv
3,201610121,2020-06-09 00:52:30,DRUG,4,DRUG,4,06/09/2020 12:52:44 AM,Y,14,06/09/2020 12:52:59 AM,...,19.0,4.0,108.0,2.0,12.0,N,N,N,N,chunk171.csv
4,200034112,2020-01-03 20:44:05,DRUG,4,DRUG,4,01/03/2020 08:44:11 PM,Y,6,01/03/2020 08:44:17 PM,...,66.0,39.0,312.0,15.0,7.0,N,N,N,N,chunk165.csv
5,200530247,2020-02-22 01:26:18,DRUG,4,DRUG,4,02/22/2020 01:27:21 AM,Y,63,02/22/2020 01:27:41 AM,...,25.0,8.0,111.0,4.0,12.0,N,N,N,N,chunk167.csv
6,200543279,2020-02-23 19:08:27,UNC,2,UNC,2,02/23/2020 07:08:44 PM,Y,17,02/23/2020 07:09:16 PM,...,44.0,8.0,204.0,9.0,15.0,N,N,N,N,chunk167.csv

In [69]:
ems2020_excerpt_df.sample(10)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
1513,200533720,2020-02-22 20:38:16,UNKNOW,4,UNKNOW,4,02/22/2020 08:38:39 PM,Y,23,02/22/2020 08:38:50 PM,...,6.0,3.0,102.0,2.0,10.0,N,N,N,N,chunk167.csv
1605,200342144,2020-02-03 12:13:51,CARDBR,2,CARDBR,2,02/03/2020 12:14:01 PM,Y,10,02/03/2020 12:14:26 PM,...,46.0,14.0,205.0,9.0,15.0,N,N,N,N,chunk166.csv
10754,200252701,2020-01-25 16:07:10,SICK,6,SICK,6,01/25/2020 04:07:28 PM,Y,18,01/25/2020 04:07:57 PM,...,120.0,49.0,501.0,31.0,11.0,N,N,N,N,chunk166.csv
5610,200100585,2020-01-10 05:32:31,SICK,6,SICK,6,01/10/2020 05:33:33 AM,Y,62,01/10/2020 05:33:59 AM,...,40.0,17.0,201.0,7.0,15.0,N,N,N,N,chunk165.csv
676,200764095,2020-03-16 20:41:36,SICPED,4,SICPED,4,03/16/2020 08:41:54 PM,Y,18,03/16/2020 08:42:25 PM,...,49.0,15.0,211.0,11.0,14.0,N,N,N,N,chunk168.csv
7709,200110592,2020-01-11 03:28:04,SICK,6,SICK,6,01/11/2020 03:28:27 AM,Y,23,01/11/2020 03:28:32 AM,...,14.0,3.0,105.0,2.0,12.0,N,N,N,N,chunk165.csv
913,201663558,2020-06-14 22:40:06,EDP,7,DRUG,4,06/14/2020 10:40:14 PM,Y,8,06/14/2020 10:40:28 PM,...,13.0,2.0,106.0,2.0,12.0,N,N,N,N,chunk171.csv
1313,201430166,2020-05-22 01:13:44,UNKNOW,4,UNKNOW,4,05/22/2020 01:13:56 AM,Y,12,05/22/2020 01:14:09 AM,...,43.0,18.0,209.0,12.0,15.0,N,N,N,N,chunk171.csv
253,200322795,2020-02-01 15:43:15,UNKNOW,4,UNKNOW,4,02/01/2020 03:46:33 PM,Y,198,02/01/2020 03:46:58 PM,...,46.0,15.0,205.0,9.0,15.0,N,N,N,N,chunk166.csv
6977,201483101,2020-05-27 19:57:23,ASTHMB,2,ASTHMB,2,05/27/2020 07:58:13 PM,Y,50,05/27/2020 07:58:28 PM,...,42.0,17.0,203.0,12.0,15.0,N,N,N,N,chunk171.csv

In [71]:
ems2020_excerpt_df.tail(6)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
13111,200870168,2020-03-27 00:42:59,INJURY,5,INJURY,5,03/27/2020 12:43:13 AM,Y,14,03/27/2020 12:43:28 AM,...,109.0,19.0,407.0,25.0,3.0,N,N,N,N,chunk168.csv
13112,200393407,2020-02-08 19:49:33,DIFFBR,2,DIFFBR,2,02/08/2020 07:52:34 PM,Y,181,02/08/2020 07:53:00 PM,...,72.0,38.0,307.0,15.0,7.0,N,N,N,N,chunk166.csv
13113,200034618,2020-01-03 22:51:33,INJURY,5,INJURY,5,01/03/2020 10:51:39 PM,Y,6,01/03/2020 10:52:21 PM,...,75.0,42.0,305.0,19.0,8.0,N,N,N,N,chunk165.csv
13114,200424355,2020-02-11 21:51:09,SICK,6,SICK,6,02/11/2020 09:52:09 PM,Y,60,02/11/2020 09:52:18 PM,...,48.0,15.0,206.0,10.0,15.0,N,N,N,N,chunk166.csv
13115,201742708,2020-06-22 15:57:44,MVAINJ,4,MVAINJ,4,06/22/2020 03:58:07 PM,Y,23,06/22/2020 03:58:19 PM,...,62.0,47.0,311.0,21.0,11.0,N,N,N,N,chunk172.csv
13116,200865674,2020-03-26 19:33:19,DIFFFC,2,DIFFFC,2,03/26/2020 07:33:50 PM,Y,31,03/26/2020 07:34:08 PM,...,103.0,27.0,412.0,29.0,5.0,N,N,N,N,chunk168.csv

In [81]:
ems2020_excerpt_df = pd.read_excel("data_raw/ems20_1st_6months_excerpt.csv", sheet_name = "FINAL_CALL_TYPE")
ems2020_excerpt_df

ValueError: Excel file format cannot be determined, you must specify an engine manually.

In [111]:
cbp_df = pd.read_excel("data_raw/multi-data.xlsx", sheet_name = "CBP")
cbp_df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
95722,2018-06-02 13:00:00,2018-06-04 09:05:00,44.066667,15-18 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
95723,2018-06-02 13:00:00,2018-06-04 09:05:00,44.066667,12-14 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
95724,2018-06-02 13:05:00,2018-06-05 23:35:00,82.483333,6-8 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
95725,2018-06-02 13:05:00,2018-06-04 00:54:00,35.8,15-18 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
95726,2018-06-02 13:20:00,2018-06-06 07:27:00,90.1,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN

In [113]:
cbp_df1 = pd.read_excel("data_raw/multi-data.xlsx", sheet_name = "CBP", skiprows = 6)
cbp_df1

,date_in,date_out,hours_in_custody,age_group,gender,citizenship,border,sector,field_office
0,2017-01-20 00:10:00,2017-01-20 10:08:00,9.950000,6-8 years,Female,EL SALVADOR,SBO,(b)(7)(E ),NaN
1,2017-01-20 00:15:00,2017-01-24 17:30:00,113.233333,3-5 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
2,2017-01-20 00:22:00,2017-01-24 17:47:00,113.416667,3-5 years,Female,BRAZIL,SBO,(b)(7)(E ),NaN
3,2017-01-20 00:30:00,2017-01-21 06:35:00,30.083333,12-14 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
4,2017-01-20 00:30:00,2017-01-21 13:03:00,36.533333,3-5 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
...,...,...,...,...,...,...,...,...,...
95716,2018-06-02 13:00:00,2018-06-04 09:05:00,44.066667,15-18 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
95717,2018-06-02 13:00:00,2018-06-04 09:05:00,44.066667,12-14 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
95718,2018-06-02 13:05:00,2018-06-05 23:35:00,82.483333,6-8 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
95719,2018-06-02 13:05:00,2018-06-04 00:54:00,35.800000,15-18 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
95720,2018-06-02 13:20:00,2018-06-06 07:27:00,90.100000,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN

In [115]:
cbp_df1.head(15)

,date_in,date_out,hours_in_custody,age_group,gender,citizenship,border,sector,field_office
0,2017-01-20 00:10:00,2017-01-20 10:08:00,9.950000,6-8 years,Female,EL SALVADOR,SBO,(b)(7)(E ),NaN
1,2017-01-20 00:15:00,2017-01-24 17:30:00,113.233333,3-5 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
2,2017-01-20 00:22:00,2017-01-24 17:47:00,113.416667,3-5 years,Female,BRAZIL,SBO,(b)(7)(E ),NaN
3,2017-01-20 00:30:00,2017-01-21 06:35:00,30.083333,12-14 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
4,2017-01-20 00:30:00,2017-01-21 13:03:00,36.533333,3-5 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
5,2017-01-20 00:30:00,2017-01-21 15:30:00,38.983333,Under 1 year,Male,HONDURAS,SBO,(b)(7)(E ),NaN
6,2017-01-20 00:35:00,2017-01-21 11:52:00,35.266667,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
7,2017-01-20 00:35:00,2017-01-20 15:14:00,14.633333,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
8,2017-01-20 00:35:00,2017-01-21 11:52:00,35.266667,3-5 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
9,2017-01-20 00:35:00,2017-01-21 11:52:00,35.266667,9-11 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
10,2017-01-20 00:45:00,2017-01-20 13:15:00,12.500000,15-18 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
11,2017-01-20 01:19:00,2017-01-21 02:30:00,25.166667,15-18 years,Male,INDIA,SBO,(b)(7)(E ),NaN
12,2017-01-20 01:19:00,2017-01-21 02:30:00,25.166667,15-18 years,Male,INDIA,SBO,(b)(7)(E ),NaN
13,2017-01-20 01:20:00,2017-01-24 17:30:00,112.166667,6-8 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
14,2017-01-20 01:20:00,2017-01-20 13:40:00,12.333333,9-11 years,Female,EL SALVADOR,SBO,(b)(7)(E ),NaN

In [117]:
cbp_df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95721 entries, 0 to 95720
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date_in           95721 non-null  datetime64[ns]
 1   date_out          95223 non-null  datetime64[ns]
 2   hours_in_custody  95506 non-null  float64
 3   age_group         95716 non-null  object
 4   gender            95721 non-null  object
 5   citizenship       95721 non-null  object
 6   border            95721 non-null  object
 7   sector            95721 non-null  object
 8   field_office      0 non-null      float64
dtypes: datetime64[ns](2), float64(2), object(5)
memory usage: 6.6+ MB

In [119]:
cbp_df1.tail(3)

,date_in,date_out,hours_in_custody,age_group,gender,citizenship,border,sector,field_office
95718,2018-06-02 13:05:00,2018-06-05 23:35:00,82.483333,6-8 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
95719,2018-06-02 13:05:00,2018-06-04 00:54:00,35.800000,15-18 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
95720,2018-06-02 13:20:00,2018-06-06 07:27:00,90.100000,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN

In [121]:
cbp_df1.sample(20)

,date_in,date_out,hours_in_custody,age_group,gender,citizenship,border,sector,field_office
41233,2017-11-18 20:00:00,2017-11-20 11:50:00,39.816667,15-18 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
1384,2017-01-23 21:22:00,2017-01-26 14:33:00,65.166667,15-18 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
92185,2018-05-24 17:49:00,2018-05-26 14:08:00,44.300000,9-11 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
12918,2017-06-01 18:40:00,2017-06-03 08:37:00,37.933333,12-14 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
82100,2018-04-26 19:30:00,2018-05-01 13:52:00,114.350000,12-14 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
73195,2018-03-28 18:00:00,2018-03-30 07:55:00,37.900000,15-18 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
58457,2018-01-27 20:20:00,2018-01-31 15:27:00,91.100000,9-11 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
7122,2017-02-27 09:30:00,2017-02-28 11:47:00,26.266667,15-18 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
62666,2018-02-17 01:30:00,2018-02-18 14:22:00,36.850000,12-14 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
31429,2017-10-03 11:45:00,2017-10-04 17:19:00,29.550000,12-14 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
21197,2017-08-05 18:20:00,2017-08-09 15:09:00,92.800000,6-8 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
30535,2017-09-27 20:30:00,2017-09-29 09:55:00,37.400000,15-18 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
28676,2017-09-16 11:00:00,2017-09-17 11:00:00,23.983333,15-18 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
61054,2018-02-09 01:17:00,2018-02-09 16:37:00,15.316667,15-18 years,Female,EL SALVADOR,SBO,(b)(7)(E ),NaN
85413,2018-05-05 23:45:00,2018-05-13 17:11:09,184.550000,1-2 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
94810,2018-05-31 02:14:00,2018-06-04 12:04:00,105.833333,9-11 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
86812,2018-05-09 23:30:00,2018-05-12 15:04:00,63.550000,15-18 years,Female,EL SALVADOR,SBO,(b)(7)(E ),NaN
27260,2017-09-08 14:50:00,2017-09-10 10:21:00,43.516667,15-18 years,Female,EL SALVADOR,SBO,(b)(7)(E ),NaN
6760,2017-02-23 02:00:00,2017-02-24 10:42:00,32.683333,12-14 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
60375,2018-02-05 19:10:00,2018-02-06 10:52:00,15.683333,15-18 years,Male,MEXICO,SBO,(b)(7)(E ),NaN

In [123]:
cbp_df1["hours_in_custody"]

0          9.950000
1        113.233333
2        113.416667
3         30.083333
4         36.533333
            ...
95716     44.066667
95717     44.066667
95718     82.483333
95719     35.800000
95720     90.100000
Name: hours_in_custody, Length: 95721, dtype: float64

In [129]:
cbp_df1["hours_in_custody"].unique()

array([  9.95      , 113.23333333, 113.41666667, ..., 100.18333333,
       126.28333333, 118.66666667])

In [131]:
cbp_df1["hours_in_custody"].nunique()

8293

In [137]:
cbp_df1["4:8"]

KeyError: '4:8'